accent = "#ff8c00"
cursor = "#ffab40"
foreground = "#f0e3d5"
background = "#181716"
selection_foreground = "#f0e3d5"
selection_background = "#7c1b00"

color0  = "#2d2a27"
color1  = "#ff3200"
color2  = "#8a9d33"
color3  = "#ffab40"
color4  = "#ff6a00"
color5  = "#ff8c00"
color6  = "#d63100"
color7  = "#d3c4b4"
color8  = "#4a4541"
color9  = "#ff5c33"
color10 = "#a3b845"
color11 = "#ffc470"
color12 = "#ff8c00"
color13 = "#ffab40"
color14 = "#ff6a00"
color15 = "#f0e3d5"
