accent = "#e5c125"
cursor = "#e5c125"
foreground = "#ede4c8"
background = "#181716"
selection_foreground = "#ede4c8"
selection_background = "#584908"

color0  = "#2d2a27"
color1  = "#d85e40"
color2  = "#8a9d33"
color3  = "#e5c125"
color4  = "#aa8f19"
color5  = "#c7a71f"
color6  = "#8e7713"
color7  = "#c9bc93"
color8  = "#4a4541"
color9  = "#e87a5c"
color10 = "#a3b845"
color11 = "#f0d75f"
color12 = "#c7a71f"
color13 = "#e5c125"
color14 = "#aa8f19"
color15 = "#ede4c8"
